service: serverless-sequelize-webpack
custom:
  webpack: 
    webpackConfig: webpack.config.js
    includeModules:
      forceInclude:
        - pg
        - pg-hstore
    packager: npm

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          path: /
          method: get
